# Módulo de Programação Python: Introdução à Linguagem

# Aula - 09

__Objetivo__:  Trabalhar com pacotes e módulos disponíveis em python: __Numpy__. Aprender a trabalhar de forma eficiente com __NumPy__ arrays utilizando as funções universais (_ufunc_) e outros recursos avançados.

## Calculando com _ndarrays_

Como já foi discutido antes, a __NumPy__ é muito utilizada, não apenas pelas características dos objetos de tipo _ndarray_, nela implementados. O conjunto de operações e funções para trabalhar com os _ndarray_ são um importante diferencial. 

Operações com arrays envolvem, na maior parte das linguagens de programação, a utilização de laços ou estruturas de repetição para percorrer os elementos dos mesmos. 

A implementação de operações vetoriais, disponíveis para o processamento de _ndarrays_ na __NumPy__, representam um diferencial importante na hora de processar estruturas de grande porte. 

Na aula anterior tentamos utilizar _ndarrays_ para implementar multiplicação de matrizes e o resultado não foi muito promisor. 

Vejamos outro exemplo para entender melhor a questão.

In [1]:
import numpy as np
from random import uniform

Vamos criar uma lista muito grande com valores aleatórios entre 1 e 100. Utilizaremos o módulo ``uniform`` do pacote ``random``.  

In [2]:
lista = [uniform(1, 100) for _ in range(1000000)]
print(lista[:3], " ...", lista[-3:])
print("len(lista) =", len(lista))

[39.48676902924606, 53.2023645955116, 40.55469578251477]  ... [32.94467008830366, 74.33439429629938, 66.09749434803942]
len(lista) = 1000000


Agora vamos testar o custo computacional de calcular o inverso de cada um dos valores das listas. 

In [3]:
lista_inv = [1/x for x in lista]
print(lista_inv[:3], " ...", lista_inv[-3:])

%timeit lista_inv = [1/x for x in lista]


[0.025324938570166256, 0.018796157043071818, 0.0246580569945035]  ... [0.030353923633766478, 0.013452722786896824, 0.015129166541994069]
31.5 ms ± 2.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Podemos fazer o mesmo experimento utilizando _ndarrays_.  

In [4]:
#array = np.random.uniform(1,100,1000000)
array = np.array(lista)
print(array[:3], " ...", array[-3:])
print("len(array) =", len(array))

[39.48676903 53.2023646  40.55469578]  ... [32.94467009 74.3343943  66.09749435]
len(array) = 1000000


In [5]:
def inv(x):
    y = np.empty_like(x)
    for i in range(len(x)):
        y[i] = 1/x[i]
    return y

array_inv = inv(array)

print(array_inv[:3], " ...", array_inv[-3:])

%timeit array_inv = inv(array)

[0.02532494 0.01879616 0.02465806]  ... [0.03035392 0.01345272 0.01512917]
113 ms ± 2.17 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Vejam que o desempenho com _ndarrays_ é pior que com listas. Este não era o resultado esperado. 

Entretanto, __NumPy__ disponibiliza uma interface apropriada que permite introduzir operações vetoriais, o que acelera significativamente o processamento de _ndarrays_ de grande porte. Compare o resultado anterior com o do exemplo a seguir.

In [6]:
#array = np.random.uniform(1,100,1000000)
array = np.array(lista)
print(array[:3], " ...", array[-3:])

array_inv = 1.0/array
print(array_inv[:3], " ...", array_inv[-3:])

%timeit array_inv = (1.0/array)

[39.48676903 53.2023646  40.55469578]  ... [32.94467009 74.3343943  66.09749435]
[0.02532494 0.01879616 0.02465806]  ... [0.03035392 0.01345272 0.01512917]
714 µs ± 35.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


As operações vetoriais são implementadas em __NumPy__ através das chamadas _ufuncs_. As _ufuncs_ são eficientes e flexíveis, permitindo realizar, de forma rápida, operações entre escalares e arrays, assim como operações entre arrays. 

Realizar os cálculos utilizando _ufuncs_ é sempre mais eficiente a implementação do mesmo cálculo utilizando estruturas de repetição. Veja os operadores aritméticos implementados em __NumPy__ através de _ufuncs_ nos exemplos a seguir.

| Operador	    | _ufunc_ equivalente | Descrição                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Adição de dois arrays ou de um array com um escalar         |
|``-``          |``np.subtract``      |Substração de dois arrays ou de um array com um escalar      |
|``-``          |``np.negative``      |Negativo unário           |
|``*``          |``np.multiply``      |Multiplicação de dois arrays ou de um array por um escalar   |
|``/``          |``np.divide``        |Divisão de dois arrays ou de um array por um escalar       |
|``//``         |``np.floor_divide``  |Divisão truncada de dois arrays ou de um array por um escalar  |
|``**``         |``np.power``         |Exponenciação  |
|``%``          |``np.mod``           |Resto da divisão |

In [ ]:
# Adição de arrays
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x + y
print(z)

# este operador adição é implementado como uma _ufunc_ (função universal) ``np.add``
print(np.add(x,y))
print("________________")
# Adição de array e escalar
z = x + 10
print(z)
print(np.add(x,10))

In [ ]:
# substração de arrays
z = x - y
print(z)

# este operador substração é implementado como uma _ufunc_ (função universal) ``np.subtract``
print(np.subtract(x,y))
print("________________")
# substração de array e escalar
z = x - 10
print(z)
print(np.subtract(x,10))

In [ ]:
# negativo
z = -z
print(z)

# este operador negativo é implementado como uma _ufunc_ (função universal) ``np.negative``
print(np.negative(z))

In [ ]:
# multiplicação de arrays
z = x * y
print(z)

# este operador multiplicação é implementado como uma _ufunc_ (função universal) ``np.multiply``
print(np.multiply(x,y))
print("________________")
# multiplicação de array e escalar
z = 2 * x
print(z)
print(np.multiply(2,x))

In [ ]:
# divisão de arrays
z = x / y
print(z)
# este operador divisão é implementado como uma _ufunc_ (função universal) ``np.divide``
print(np.divide(x,y))
print("________________")
# divisão de array e escalar
z = x / 2
print(z)
print(np.divide(x,2))


In [ ]:
# divisão truncada de arrays
z = x // y
print(z)
# este operador divisão é implementado como uma _ufunc_ (função universal) ``np.divide``
print(np.floor_divide(x,y))
print("________________")
# divisão truncada de array e escalar
z = x // 2
print(z)
print(np.floor_divide(x,2))

In [ ]:
# exponenciação de arrays
z = x ** y
print(z)
# este operador divisão é implementado como uma _ufunc_ (função universal) ``np.power``
print(np.power(x,y))
print("________________")
# exponenciação de array e escalar
z = x ** 2
print(z)
print(np.power(x,2))

In [ ]:
# resto da divisão de arrays
z = x % y
print(z)
# este operador divisão é implementado como uma _ufunc_ (função universal) ``np.mod``
print(np.mod(x,y))
print("________________")
# resto da divisão de array e escalar
z = x % 2
print(z)
print(np.mod(x,2))

Além deste conjunto básico de operadores, implementados na furma de _unfunc_ que sobrecarregam os operadores aritméticos tradicionais, __NumPy__ disponibiliza um conjunto adicional de funções:

|Nome da Função     |   Descrição                                   |
|:-------------------:|-----------------------------------------------|
| ``np.abs``<br>ou<br>``np.absolute``| Retorna o valor absoluto dos elementos do<br>_ndarray_. Também funciona com _ndarrays_ de<br>números complexos.     |

In [ ]:
# valor absoluto 
x = np.array([-1.2,2.3,-3.4])
z = np.abs(x)
print(z)
# este operador divisão é implementado como uma _ufunc_ (função universal) ``np.absolute``
print(np.absolute(x))
#ou
print(np.abs(x))
# No caso de números complexos, o valor absoluto é a magnitude
x = np.array([-1+1j,2-2j,-3+3j])
z = np.abs(x)
print(z)


Funções Trigonométricas

|Nome da Função     |   Descrição                                     |
|:-------------------:|-----------------------------------------------|
| ``np.sin``          | Retorna o seno dos elementos do array         |
| ``np.cos``          | Retorna p cosseno dos elementos do array      |
| ``np.tan``          | Retorna a tangente dos elementos do array     |
| ``np.arcsin``       | Retorna o arco-seno dos elementos do array    |
| ``np.arccos``       | Retorna o arco-cosseno dos elementos do array |
| ``np.arctan``       | Retorna a arco-tangente dos elementos do array    |

In [ ]:
ang = np.linspace(0,2*np.pi,25) # ângulos em radianos
#print(ang)
print(np.rad2deg(ang)) # ângulos em graus


In [ ]:
print("Seno: \n", np.sin(ang))
print("Cosseno: \n", np.cos(ang))
print("Tangente: \n", np.tan(ang))

In [ ]:
print("Arco seno: \n", np.rad2deg(np.arcsin(np.sin(ang))))
print("Arco cosseno: \n", np.rad2deg(np.arccos(np.cos(ang))))
print("Arco tangente: \n", np.rad2deg(np.arctan(np.tan(ang))))

Funções exponenciais e logarítmicas

|Nome da Função     |   Descrição                                     |
|:-------------------:|-----------------------------------------------|
| ``np.exp``          | Retorna $e^x$         |
| ``np.exp2``         | Retorna $2^x$      |
| ``np.power``        | Retorna $a^x$     |
| ``np.ln``           | Retorna $\log_e x$ ou simplesmente $\ln x$    |
| ``np.log2``         | Retorna $\log_2 x$  |
| ``np.log10``        | Retorna $\log_{10} x$ |

In [ ]:
x = np.array([1,2,3])
print("Exponencial (e**x): \n", np.exp(x))
print("Exponencial (2**x): \n", np.exp2(x))
print("Exponencial (10**x): \n", np.power(10,x))

In [ ]:
print("Logaritmo natural: \n", np.log(np.exp(x)))
print("Logaritmo base 2: \n", np.log2(np.exp2(x)))
print("Logaritmo base 10: \n", np.log10(np.power(10,x)))

In [ ]:
#outros logaritmos
#log base 3 de x pode ser calculado como log(x)/log(3)
print("Logaritmo base 3: \n", np.log(np.power(3,x))/np.log(3))

As limitações impostas pela aritmética de ponto flutuante faz com que, em alguns casos, seja necessário utilizar artifícios matemáticos para melhorar a precisão dos resultados. Para estes casos a __NumPy__ disponibiliza funções especiais como a utilizada no seguinte exemplo. 

In [ ]:
x = np.array([0, 0.001, 0.01, 0.1])
print("Exponencial (e**x): \n", np.exp(x))
print("Exponencial (e**x - 1): \n", np.expm1(x))
#print("Logaritmo natural: \n", np.log(x))
print("Logaritmo natural (1 + x): \n", np.log1p(x))

Para valores do argumento muito pequenos estas funções conseguem retornar um resultado com maior precisão. 

MAs vamos retomar o exemplo do final da aula anterior 

Relembrando a definição de GEMM que implementa a seguinte operação

$C = \alpha AB + \beta C$ 

De forma que:

$C[i,j] = \alpha \sum_{k=0}^{k<l} {A[i,k] B[k,j]} + \beta C[i,j]$

Vamos primeiramente revisar a implementação baseada exclusivamente no uso de estruturas de repetição.

In [7]:
#Esta é uma implementação específica para ndarrays
def GEMM_loops(alpha, A, B, beta, C):
    ma, la = A.shape
    lb, nb = B.shape
    mc, nc = C.shape
    if (ma != mc) or (la != lb) or (nb != nc):
        return C
    
    for i in range(mc):
        for j in range(nc):
            val = 0
            for k in range(la):
                val += A[i,k]*B[k,j]
            C[i,j] = alpha*val + beta*C[i,j]
    return C

In [8]:
# Dada uma matriz A de n linhas e l colunas
n = 256
l = 128
A = np.random.random((n,l))
#A = np.ones((n,l))
# Uma matriz B de l linhas e n colunas
m = 256
B = np.random.random((l,m))
#B= np.ones((l,m))
# Uma matriz C de n linhas e m colunas
#C = np.ones((n,m))
#C = np.zeros((n,m))
C = np.random.random((n,m))
# E os escalares alpha e beta
alpha = 0.5
#alpha = 1.0
beta = 1.5
#beta = 1.0
#print(A)
#print(B)
#print(C)

In [9]:
C1 = C.copy()
%timeit Z = GEMM_loops(alpha, A, B, beta, C1)
C1 = GEMM_loops(alpha, A, B, beta, C1)

1.48 s ± 50.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Podemos então tentar usar a _ufunc_ para melhorar o desempenho

In [10]:
def GEMM_ufunc1(alpha, A, B, beta, C):
    ma, la = A.shape
    lb, nb = B.shape
    mc, nc = C.shape
    if (ma != mc) or (la != lb) or (nb != nc):
        return C
    
    C = beta * C
    for i in range(mc):
        for j in range(nc):
            val = 0
            for k in range(la):
                val += A[i,k]*B[k,j]
            C[i,j] += alpha*val

    return C

In [11]:
C2 = C.copy()
%timeit Z = GEMM_ufunc1(alpha, A, B, beta, C2)
C2= GEMM_ufunc1(alpha, A, B, beta, C2)

1.48 s ± 53 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [12]:
def GEMM_ufunc2(alpha, A, B, beta, C):
    ma, la = A.shape
    lb, nb = B.shape
    mc, nc = C.shape
    if (ma != mc) or (la != lb) or (nb != nc):
        return C
    
    C = beta * C
    for i in range(mc):
        for j in range(nc):
            C_ = A[i,:] * B[:,j].T
            val = 0
            for k in range(la):
                val += C_[k]
            C[i,j] += alpha*val
    
    return C

In [13]:
C3 = C.copy()
%timeit Z = GEMM_ufunc2(alpha, A, B, beta, C3)
C3= GEMM_ufunc2(alpha, A, B, beta, C3)

647 ms ± 24.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Queda significativa no tempo total de processamento. Podemos melhorar ainda mais?

Quando trabalhamos com uma grande quantidade de dados, muitas vezes se faz necessário começar par fazer uma análise estatística dos mesmos, 

Algumas métricas utilizadas em estatística, como as medidas de valor central ou as medidas de espalhamento, ou ainda medidas de correlação, podem ser um necessárias.

De forma geral a média e o desvio pdrão é bom ponto de partida. 

__NumPy__ disponibiliza funções de agregação integradas rápidas para trabalhar em _ndarrays_ que são muito relevantes, por exemplo, para este tipo de análises.

Podemos começar pelo algoritmo simples, que já foi utilizado anteriormente, para calcular a soma de um conjunto de elementos, por exemplo, para calcular a média do conjunto. 

Se os valores estão numa lista, podemos utilizar a função ``sum``

In [14]:
from random import random   
matSize = 512
vetX = [random() for i in range(matSize)]
soma = sum(vetX)
print(soma)

262.0302623576084


Podemos obter o mesmo resultado utilizando os recursos da __NumPy__, particularmente a função ``sum`` 

In [15]:
#import numpy as np
x = np.array(vetX)
soma = np.sum(x)
print(soma)

262.0302623576082


Vamos comparar o desempenho destas duas implementações.

In [16]:
matSize = 1000000
vetX = [random() for i in range(matSize)]
x = np.array(vetX)
%timeit sum(vetX)
%timeit np.sum(x)

2.63 ms ± 16.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
188 µs ± 672 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


Repare que esta função pode ser utilizada na nossa implementação da para _ndarrays_ do __GEMM__.

In [17]:
def GEMM_ufunc3(alpha, A, B, beta, C):
    ma, la = A.shape
    lb, nb = B.shape
    mc, nc = C.shape
    if (ma != mc) or (la != lb) or (nb != nc):
        return C
    
    C = beta * C
    for i in range(mc):
        for j in range(nc):
            C[i,j] += alpha*np.sum(A[i,:] * B[:,j].T)
    
    return C

In [18]:
C4 = C.copy()
%timeit Z = GEMM_ufunc3(alpha, A, B, beta, C4)
C4= GEMM_ufunc3(alpha, A, B, beta, C4)

134 ms ± 430 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


No exercício da prova do módulo anterior utilizamos as funções ``min`` e ``max``, que também tem implementações muito eficientes na __NumPy__

In [ ]:
print(max(vetX))
print(np.max(x))
%timeit max(vetX)
%timeit np.max(x)

In [ ]:
print(min(vetX))
print(np.min(x))
%timeit min(vetX)
%timeit np.min(x)

Este tipo de funções são chamadas de funções agregadoras. Outras funções de agregação estão disponíveis. A maioria delas uma versão segura para __NaN__, que calcula o resultado ignorando os valores ausentes, que são marcados pelo valor __NaN__ de ponto flutuante. Algumas dessas funções seguras para NaN não foram adicionadas até o NumPy 1.8, portanto, não estarão disponíveis em versões mais antigas do NumPy. Veja a tabela a seguir.

|Função             |   Versão __NaN-__safe  | Descrição                                  |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Calcula a soma dos elementos                  |
| ``np.prod``       | ``np.nanprod``      | Calcula o produto dos elementos               |
| ``np.mean``       | ``np.nanmean``      | Calcula o valor médio                         |
| ``np.std``        | ``np.nanstd``       | Calcula o desvio padrão                       |
| ``np.var``        | ``np.nanvar``       | Calcula a variância                              |
| ``np.min``        | ``np.nanmin``       | Retorna o valor mínimo                            |
| ``np.max``        | ``np.nanmax``       | Retorna o valor máximo                            |
| ``np.argmin``     | ``np.nanargmin``    | Retorna o índice de valor mínimo                   |
| ``np.argmax``     | ``np.nanargmax``    | Retorna o índice de valor máximo                   |
| ``np.median``     | ``np.nanmedian``    | Calcula a mediana                    |
| ``np.percentile`` | ``np.nanpercentile``| Calcula os percentil      |
| ``np.any``        | N/A                 | Avalie se algum elemento é verdadeiro        |
| ``np.all``        | N/A                 | Avalie se todos os elementos são verdadeiros        |

Estas funções permitam trabalhar com arrays multidimensionais.

In [19]:
A = np.random.random((3,3))
print(A)
print("Soma: ", np.sum(A))
print("Máximo: ", np.max(A))
print("Índice do máximo: ", np.argmax(A))
print("Mínimo: ", np.min(A))
print("Índice do mínimo: ", np.argmin(A))
print("Média: ", np.mean(A))
print("Mediana: ", np.median(A))
print("Desvio padrão: ", np.std(A))


[[0.10985145 0.78976879 0.24880594]
 [0.58370978 0.43162229 0.56784293]
 [0.8705896  0.98628158 0.32895774]]
Soma:  4.917430101720881
Máximo:  0.9862815780714174
Índice do máximo:  7
Mínimo:  0.10985145057537193
Índice do mínimo:  0
Média:  0.5463811224134312
Mediana:  0.5678429285183658
Desvio padrão:  0.2787405814342637


As funções de agregação pode receber também um argumento adicional que especifica o eixo ao longo do qual a agregação deve ser calculada. Por exemplo, podemos encontrar o valor máximo de cada coluna especificando ``axis=0``, e de cada linha especificando ``axis=1``

In [20]:
print(A)
print("Soma: ", np.sum(A, axis=0))
print("Máximo: ", np.max(A, axis=0))
print("Índice do máximo: ", np.argmax(A, axis=0))
print("Mínimo: ", np.min(A, axis=0))
print("Índice do mínimo: ", np.argmin(A, axis=0))
print("Média: ", np.mean(A, axis=0))
print("Mediana: ", np.median(A, axis=0))
print("Desvio padrão: ", np.std(A, axis=0))

[[0.10985145 0.78976879 0.24880594]
 [0.58370978 0.43162229 0.56784293]
 [0.8705896  0.98628158 0.32895774]]
Soma:  [1.56415083 2.20767266 1.14560661]
Máximo:  [0.8705896  0.98628158 0.56784293]
Índice do máximo:  [2 2 1]
Mínimo:  [0.10985145 0.43162229 0.24880594]
Índice do mínimo:  [0 1 0]
Média:  [0.52138361 0.73589089 0.38186887]
Mediana:  [0.58370978 0.78976879 0.32895774]
Desvio padrão:  [0.31368142 0.22962122 0.13551344]


Temos ainda a implementação dos produtos vetoriais e matrizais da álgebra linear. 

A função ``np.dot`` implementa o produto escalar de duas matrizes. 

* Se ``a`` e ``b`` são matrizes 1-D, o resultado é o produto interno de vetores (sem complexa conjugada).

* Se ``a`` e ``b`` forem matrizes 2-D, o resultado é uma multiplicação de matrizes, mas é preferível usar ``matmul`` ou ``a @ b``.

Se ``a`` ou ``b`` for escalar, é equivalente a multiplicar e usar ``numpy.multiply(a, b)`` ou ``a * b``.

In [21]:
x = np.array([1,2,3])
y = np.array([4,5,6])

z = np.dot(x,y)
print(z)

32


In [22]:
A = np.random.random((3,3))
B = np.random.random((3,3))

C = np.dot(A,B)
print(C)

[[0.36140495 0.89938454 0.59608409]
 [1.08612001 0.93760186 0.89801676]
 [0.64695178 1.13316198 0.58697666]]


Podemos retomar nossa implementação a GEMM para usar o produto escalar de vetores.

In [23]:
# Dada uma matriz A de n linhas e l colunas
n = 256
l = 128
A = np.random.random((n,l))
#A = np.ones((n,l))
# Uma matriz B de l linhas e n colunas
m = 256
B = np.random.random((l,m))
#B= np.ones((l,m))
# Uma matriz C de n linhas e m colunas
#C = np.ones((n,m))
#C = np.zeros((n,m))
C = np.random.random((n,m))
# E os escalares alpha e beta
alpha = 0.5
#alpha = 1.0
beta = 1.5
#beta = 1.0
#print(A)
#print(B)
#print(C)

In [24]:
def GEMM_ufunc4(alpha, A, B, beta, C):
    ma, la = A.shape
    lb, nb = B.shape
    mc, nc = C.shape
    if (ma != mc) or (la != lb) or (nb != nc):
        return C
    
    C = beta * C
    for i in range(mc):
        for j in range(nc):
            C[i,j] += alpha*np.dot(A[i,:],B[:,j].T)
    
    return C

In [25]:
C5 = C.copy()
%timeit Z = GEMM_ufunc4(alpha, A, B, beta, C5)
C5= GEMM_ufunc4(alpha, A, B, beta, C4)

55.7 ms ± 437 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [26]:
%timeit Z = alpha*np.dot(A,B)+beta*C
print((alpha*np.dot(A,B)+beta*C).shape)

570 µs ± 114 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
(256, 256)


In [27]:
%timeit Z = alpha*np.matmul(A,B) + beta*C
print((alpha*np.matmul(A,B) + beta*C).shape)

617 µs ± 302 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
(256, 256)


In [28]:
%timeit Z = alpha*A@B + beta*C
print((alpha*A@B + beta*C).shape)

608 µs ± 118 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
(256, 256)


In [29]:
# Dada uma matriz A de n linhas e l colunas
n = 1024
l = 1024
A = np.random.random((n,l))
#A = np.ones((n,l))
# Uma matriz B de l linhas e n colunas
m = 1024
B = np.random.random((l,m))
#B= np.ones((l,m))
# Uma matriz C de n linhas e m colunas
#C = np.ones((n,m))
#C = np.zeros((n,m))
C = np.random.random((n,m))
# E os escalares alpha e beta
alpha = 0.5
#alpha = 1.0
beta = 1.5
#beta = 1.0
#print(A)
#print(B)
#print(C)

In [30]:
%timeit Z = GEMM_ufunc4(alpha, A, B, beta, C)

2.4 s ± 94.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
gflop = (2.0*1024 + 2)*(1024**2)*1E-9
print(gflop/7.98)

In [31]:
%timeit Z = alpha*np.dot(A,B)+beta*C

45.8 ms ± 11.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [32]:
print(gflop/(29*1E-3))

NameError: name 'gflop' is not defined

In [33]:
%timeit Z = alpha*np.matmul(A,B) + beta*C

39.5 ms ± 8.26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [34]:
%timeit Z = alpha*A@B + beta*C

32.9 ms ± 6.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
